---
# install
# add cluster
# add applications


- name: Install argocd
  when: inventory_hostname == groups['controlplane'][0]
  block:
    - name: Add argo chart repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm
        kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    
    - name: Deploy argocd
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        create_namespace: true
        chart_version: "{{ argocd_version | default(omit) }}"
        kubeconfig: "/home/{{ ansible_user }}/.kube/config"
        

- name: Configure argocd
  when: inventory_hostname == groups['controlplane'][0]
  block:
    - name: Apply application manifest
      kubernetes.core.k8s:
        kubeconfig: "/home/{{ ansible_user }}/.kube/config"
        state: present
        definition: "{{ lookup('template', 'application.yml.j2') | from_yaml }}"
