- name: Ensure required packages are installed
  ansible.builtin.dnf:
    name:
      - sudo
      - dnf-plugins-core
      - epel-release
      - python3-pip
      - git
    state: present
    best: false
    enablerepo:
      - crb
    disablerepo:
      - epel
- name: Add Docker CE repository
  ansible.builtin.copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "0755"
  notify: Restart docker
- name: Install docker 
  ansible.builtin.dnf:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present
    