---
- name: Create a cluster
  hosts: '{{target|default("controlplane:worker")}}'
  become: true
  tasks:
    - name: Make Cluster
      ansible.builtin.include_role:
        name: dialgatrainer02_lab.homelab.k8_cluster

    # later to argo cd decorations
    - name: Install argocd
      ansible.builtin.include_role:
        name: dialgatrainer02_lab.homelab.argocd
      vars:
        argocd_application_path: decorations
        argocd_application_name: decorations
        argocd_application_auto_sync: true
    - name: Install argocd
      ansible.builtin.include_role:
        name: dialgatrainer02_lab.homelab.argocd
