---
- name: Create a cluster
  hosts: '{{target|default("all")}}'
  become: true
  tasks:
    - name: Make Cluster
      ansible.builtin.include_role:
        name: dialgatrainer02_lab.homelab.k8_cluster

    # later to argo cd
    - name: Install argocd
      ansible.builtin.include_role:
        name: dialgatrainer02_lab.homelab.argocd
