---
- name: Create a dns server
  hosts: '{{target|default("dns")}}'
  become: true
  vars:
    config_dir: /opt/dns
  tasks:
    - name: Install packages
      tags:
        - packages
      block:
        - name: Ensure required packages are installed
          ansible.builtin.dnf:
            name:
              - sudo
              - dnf-plugins-core
              - epel-release
              - python3-pip
              - git
            state: present
            enablerepo:
              - crb
        - name: Add Docker CE repository
          ansible.builtin.copy:
            src: docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo
            mode: "0755"
        - name: Install docker 
          ansible.builtin.dnf:
            name:
              - docker-ce 
              - docker-ce-cli 
              - containerd.io 
              - docker-buildx-plugin 
              - docker-compose-plugin
            state: present
    - name: Use nftables
      ansible.builtin.copy:
        src: deamon.json
        dest: /etc/docker/daemon.json
    - name: Enable ip forwarding
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        reload: true
        sysctl_file: /etc/sysctl.d/k8s.conf
      loop:
        - { name: "net.ipv6.conf.all.forwarding", value: "1" }
        - { name: "net.ipv4.ip_forward", value: "1" }
    - name: Start docker
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: yes
    - name: make config dir
      ansible.builtin.file:
        state: directory
        path: "{{ config_dir }}"
    - name: copy files
      ansible.builtin.copy:
        dest: "{{ config_dir }}/{{ item }}"
        src: "{{ item }}"
      loop:
        - docker-compose.yml
        - Corefile
        - unbound.conf
    - name: start docker compose
    # shoudl use docker compose module
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: "{{ config_dir }}"
        
    