- name: Create kubernetes secrets for apps
  hosts: '{{target|default("all")}}'
  become: trueobjects

  tasks:
    - name: Etcd
      when: inventory_hostname == groups['controlplane'][0]
      block:
        - name: Get an existing Secret object
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Secret
            name: "{{ secret_openbao_namespace }}"
            namespace: "{{ secret_openbao_namespace }}"
          register: ansible_password
        - name: login
          community.hashi_vault.vault_login:
            auth_method: userpass
            username: ansible
            password: "{{ ansible_password.resources[0].password }}"
          register: login
        
        - name: get secret
          community.hashi_vault.vault_read:
            token: '{{ login | community.hashi_vault.vault_login_token }}'
            path: 'secrets/data/my-secret'
          register: secret