- name: Create kubernetes secrets for apps
  hosts: '{{target|default("all")}}'
  become: true
  tasks:
    - name: Etcd
      when: inventory_hostname == groups['controlplane'][0]
      block:
        - name: Etcd url
          kubernetes.core.k8s:
            definition:
              kind: secret
              metadata: 
                name: etcd-urls
                annotations:
                  ansible: true
              stringData:
                urls: "http://{{ hostvars['dns0']['inventory_hostname'] }}:2379" 