---
- name: Create a dns server
  hosts: '{{target|default("dns")}}'
  become: true
  tasks:
    - name: Install unbound
      ansible.builtin.dnf:
        name:
          - unbound
    - name: Make unbound config dir
      ansible.builtin.file:
        name: /etc/unbound/unbound.conf.d
        state: directory
    - name: Get root hints
      ansible.builtin.get_url:
        url: https://www.internic.net/domain/named.cache
        dest: /var/lib/unbound/root.hints
    - name: Set up trust anchor
      ansible.builtin.command:
        cmd: sudo -u unbound  unbound-anchor
        creates: "/var/lib/unbound/root.key"
    - name: Generate unbound config
      ansible.builtin.copy:
        src: 99-unbound.conf
        dest: /etc/unbound/unbound.conf.d/99-unbound.conf
    # - name: Set up remote control
      # ansible.builtin.command:
        # cmd: sudo -u unbound unbound-control-setup
        # creates: /usr/local/etc/unbound/unbound_server.key
    - name: start unbound
      ansible.builtin.systemd_service:
        name: unbound
        enabled: yes
        state: started